apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-jobmanager
  namespace: stream
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink
      component: jobmanager
  template:
    metadata:
      labels:
        app: flink
        component: jobmanager
    spec:
      initContainers:
        - name: init-db
          image: postgres:16
          command: ['sh', '-c']
          args:
            - |
              until psql $my_postgres_conn -c '\q'; do
                echo "Đang đợi Postgres tại $my_postgres_conn..."
                sleep 5
              done
              psql $my_postgres_conn -f /opt/flink/usrlib/init.sql
          env:
            - name: my_postgres_conn
              value: "postgres://hiveuser:hivepassword@postgres-service.data-storage.svc.cluster.local:5432/ecom_Db"
          volumeMounts:
          - name: flink-config-volume
            mountPath: /opt/flink/usrlib/init.sql
            subPath: init.sql
      containers:
        - name: jobmanager
          image: allocknguyen/flink-ml-full:v3
          args: ["jobmanager"]
          env:
            - name: FLINK_PROPERTIES
              value: |
                jobmanager.rpc.address: flink-jobmanager
                jobmanager.rpc.port: 6123
                jobmanager.memory.process.size: 1024m
                jobmanager.bind-host: 0.0.0.0
                rest.port: 8081
                blob.server.port: 6124
                parallelism.default: 2
                taskmanager.numberOfTaskSlots: 2
                state.backend: rocksdb
                state.checkpoints.dir: file:///tmp/flink-checkpoints
                execution.checkpointing.interval: 10s
                s3.endpoint: http://my-minio.data-storage:9000
                s3.access-key: admin
                s3.secret-key: admin123
                s3.path.style.access: true
          ports:
            - containerPort: 6123 # RPC
            - containerPort: 8081 # REST UI
            - containerPort: 6124 # Blob Server
          volumeMounts:
            - name: flink-config-volume
              mountPath: /opt/flink/usrlib/init.sql
              subPath: init.sql
            - name: flink-config-volume
              mountPath: /opt/flink/usrlib/fraud_prediction.py
              subPath: fraud_prediction.py
            - name: flink-config-volume
              mountPath: /opt/flink/usrlib/fraud_model.json
              subPath: fraud_model.json
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      volumes:
        - name: flink-config-volume
          configMap:
            name: flink-config
            items:
              - key: init.sql           
                path: init.sql
              - key: fraud_prediction.py  
                path: fraud_prediction.py
              - key: fraud_model.json
                path: fraud_model.json