apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-taskmanager
  namespace: stream
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink
      component: taskmanager
  template:
    metadata:
      labels:
        app: flink
        component: taskmanager
    spec:
      containers:
        - name: taskmanager
          image: allocknguyen/flink-ml-full:v3
          args: ["taskmanager"]
          ports:
            - containerPort: 6121
          resources:
            limits:
              memory: "4Gi"   
              cpu: "1000m"
            requests:
              memory: "2Gi"
              cpu: "500m"
          volumeMounts:
            - name: config-volume
              mountPath: /opt/flink/conf/flink-conf.yaml
              subPath: flink-conf.yaml
            - name: flink-config-volume
              mountPath: /opt/flink/usrlib/init.sql
              subPath: init.sql
            - name: flink-config-volume
              mountPath: /opt/flink/usrlib/fraud_prediction.py
              subPath: fraud_prediction.py
            - name: flink-config-volume
              mountPath: /opt/flink/usrlib/fraud_model.json
              subPath: fraud_model.json
      volumes:
        - name: config-volume
          configMap:
            name: flink-config
            # Khai báo rõ ràng key nào trong ConfigMap sẽ được dùng
            items:
              - key: flink-conf.yaml
                path: flink-conf.yaml
        - name: flink-config-volume
          configMap:
            name: flink-config