{
 "title": "DB_Dashboard Copy",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Number of potentially fraudulent transactions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "ecom_Db",
     "rawSql": "SELECT\n  count(is_fraud_predicted)\nFROM fraud_alerts\nwhere is_fraud_predicted = 1"
    }
   ]
  },
  {
   "title": "Number of potentially fraudulent transactions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "ecom_Db",
     "rawSql": "SELECT\n  count(is_fraud_predicted)\nFROM fraud_alerts"
    }
   ]
  },
  {
   "title": "Top 5 Most Fraudulent Payment Methods",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "dataset": "ecom_Db",
     "rawSql": "SELECT\n  payment_method AS \"Phương thức\",\n  count(*) AS \"Số vụ\"\nFROM fraud_alerts\nWHERE is_fraud_predicted = 1\nGROUP BY payment_method\nORDER BY 2 DESC\nLIMIT 5;"
    }
   ]
  },
  {
   "title": "Fraudulent Transaction Rate vs. Normal Transaction Rate",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "ecom_Db",
     "rawSql": "SELECT\n  CASE \n    WHEN is_fraud_predicted = 1 THEN '🚨 Gian lận'\n    ELSE '✅ An toàn' \n  END as \"Trạng thái\",\n  count(*) as \"Số lượng GD\"\nFROM fraud_alerts\n-- WHERE $__timeFilter(alert_time) -- Bỏ comment nếu muốn lọc theo thời gian trên thanh công cụ\nGROUP BY is_fraud_predicted;"
    }
   ]
  },
  {
   "title": "Number of fraud cases over time",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 13, "x": 11, "y": 8 },
   "targets": [
    {
     "dataset": "ecom_Db",
     "rawSql": "SELECT\n  alert_time AS \"time\",\n  count(*) AS \"Số vụ gian lận\"\nFROM fraud_alerts\nWHERE is_fraud_predicted = 1\nGROUP BY 1\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Total amount of money lost due to fraud.",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "ecom_Db",
     "rawSql": "SELECT\n  sum(amount) as \"Tổng tiền gian lận (USD)\"\nFROM fraud_alerts\nWHERE is_fraud_predicted = 1;"
    }
   ]
  }
 ]
}