# 1. Cấu hình Database (Giữ nguyên vì đã đúng)
postgresql:
  enabled: true
  auth:
    username: postgres
    password: postgres
    database: postgres

  image:
    repository: postgres
    tag: 15-alpine
    pullPolicy: IfNotPresent

data:
  metadataConnection:
    user: postgres
    pass: postgres
    db: postgres
    host: airflow-postgresql
    port: 5432
  

# 2. Cấu hình Image (DÙNG IMAGE BẠN ĐÃ BUILD)
images:
  airflow:
    repository: allocknguyen/airflow
    tag: v7
    pullPolicy: IfNotPresent
# Đừng dùng apache/airflow:latest nữa, nó thiếu thư viện!

apiServer:
  enabled: true
  resources:
    requests:
      cpu: "200m"
      memory: "1Gi"
    limits:
      cpu: "1000m"
      memory: "2Gi"

webserver:
  command: ["airflow", "webserver"]
  enabled: true
  replicas: 1
  defaultUser:
    enabled: true
    role: Admin
    username: admin
    password: admin
  resources:
    requests:
      cpu: "200m"
      memory: "1Gi"
    limits:
      cpu: "1000m"
      memory: "2Gi"
  startupProbe:
    failureThreshold: 60
    periodSeconds: 10

# Áp dụng cho Scheduler
scheduler:
  resources:
    requests:
      cpu: "200m"
      memory: "1Gi"
    limits:
      cpu: "1000m"
      memory: "2Gi"

# 4. GitSync (Giữ nguyên)
dags:
  gitSync:
    enabled: true
    repo: "https://github.com/alloc110/Analysis_Ecom_Real_Time.git"
    branch: "main"
    rev: "HEAD"
    depth: 1
    wait: 60
    subPath: "dags"

  # Giữ nguyên các phần resources/replicas của bạn...

# 1. Khai báo cho Helm tạo Secret (nếu dùng Helm chart mặc định)
webserverSecretKey: "PP4RF2gNXxIABjQ1FroMOdO9JjdpAwdP"

config:
  # 2. Section cũ (cho Webserver UI)
  webserver:
    secret_key: "PP4RF2gNXxIABjQ1FroMOdO9JjdpAwdP"
    
  # 3. Section MỚI (Đây là nơi gây ra lỗi bạn vừa gửi)
  api:
    auth_jwt_secret: "PP4RF2gNXxIABjQ1FroMOdO9JjdpAwdP"
    # Đôi khi Airflow 3 yêu cầu cả dòng này nếu bạn cấu hình thủ công:
    secret_key: "PP4RF2gNXxIABjQ1FroMOdO9JjdpAwdP"

serviceAccount:
  create: true
  name: "airflow-worker-sa"

# Gắn ServiceAccount này vào Scheduler và Worker
scheduler:
  serviceAccount:
    name: "airflow-worker-sa"
    
worker:
  serviceAccount:
    name: "airflow-worker-sa"


extraEnv: |
  - name: AIRFLOW_CONN_MY_POSTGRES_CONN
    value: "postgres://hiveuser:hivepassword@postgres-service.data-storage.svc.cluster.local:5432/ecom_Db"