apiVersion: kafka.strimzi.io/v1
kind: KafkaConnect
metadata:
  name: my-connect-cluster
  namespace: stream
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 4.3.0
  replicas: 1

  bootstrapServers: my-cluster-kafka-bootstrap:9092
  groupId: connect-cluster
  configStorageTopic: connect-configs
  offsetStorageTopic: connect-offsets
  statusStorageTopic: connect-status

  config:
    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1

  build:
    output:
      type: docker
      image: allocknguyen/my-connect:latest
    plugins:
      - name: debezium-postgres
        artifacts:
          - type: tgz
            url: https://repo1.maven.org/maven2/io/debezium/debezium-connector-postgres/2.6.0.Final/debezium-connector-postgres-2.6.0.Final-plugin.tar.gz