apiVersion: kafka.strimzi.io/v1
kind: KafkaConnect
metadata:
  name: my-connect-cluster
  namespace: stream
  annotations:
    strimzi.io/use-connector-resources: "true"

spec:
  version: 4.3.0
  replicas: 1

  image: allocknguyen/my-connect:latest

  bootstrapServers: my-cluster-kafka-bootstrap:9092

  groupId: connect-cluster

  configStorageTopic: connect-configs
  offsetStorageTopic: connect-offsets
  statusStorageTopic: connect-status

  config:
    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1

    # Converter cho Debezium JSON
    key.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter

    key.converter.schemas.enable: false
    value.converter.schemas.enable: false