apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
  namespace: stream
spec:
  kafka:
    version: 3.7.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      min.insync.replicas: 1
    storage:
      type: persistent-claim
      size: 10Gi # Cấp 10GB không gian riêng cho Kafka
      deleteClaim: false # (Tùy chọn) Giữ lại dữ liệu kể cả khi bạn lỡ tay xóa cụm Kafka
  entityOperator:
    topicOperator: {}
    userOperator: {}