apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: dual-role
  namespace: stream
  labels:
    strimzi.io/cluster: my-cluster
spec:
  replicas: 1
  roles:
    - controller
    - broker
  storage:
    type: persistent-claim
    size: 10Gi # Cấp 10GB không gian riêng cho Kafka
    deleteClaim: false # (Tùy chọn) Giữ lại dữ liệu kể cả khi bạn lỡ tay xóa cụm Kafka
  resources:
    requests:
      memory: 512Mi
      cpu: 200m
    limits:
      memory: 1Gi
      cpu: 500m

  